spring.config.import=optional:file:.env[.properties]

# Exchange y Queue
rabbitmq.exchange.commercial=${RABBITMQ_EXCHANGE_COMMERCIAL: commercial.exchange}
rabbitmq.queue.purchase=${RABBITMQ_QUEUE_PURCHASE: purchase.queue}
rabbitmq.routing-key.purchase=${RABBITMQ_ROUTING_KEY_PURCHASE: purchase.received}
# Sales Create
rabbitmq.exchange.sales-create-request=${RABBITMQ_EXCHANGE_SALES_CREATE_REQUEST:sales.create.request.exchange}
rabbitmq.queue.sales-create-request=${RABBITMQ_QUEUE_SALES_CREATE_REQUEST:sales.create.request.queue}
rabbitmq.routing-key.sales-create-request=${RABBITMQ_ROUTING_KEY_SALES_CREATE_REQUEST:sales.create.request}
# Sales Update
rabbitmq.exchange.sales-update-request=${RABBITMQ_EXCHANGE_SALES_UPDATE_REQUEST:sales.update.request.exchange}
rabbitmq.queue.sales-update-request=${RABBITMQ_QUEUE_SALES_UPDATE_REQUEST:sales.update.request.queue}
rabbitmq.routing-key.sales-update-request=${RABBITMQ_ROUTING_KEY_SALES_UPDATE_REQUEST:sales.update.request}
# Sales Patch
rabbitmq.exchange.sales-patch-request=${RABBITMQ_EXCHANGE_SALES_PATCH_REQUEST:sales.patch.request.exchange}
rabbitmq.queue.sales-patch-request=${RABBITMQ_QUEUE_SALES_PATCH_REQUEST:sales.patch.request.queue}
rabbitmq.routing-key.sales-patch-request=${RABBITMQ_ROUTING_KEY_SALES_PATCH_REQUEST:sales.patch.request}
# Sales Delete
rabbitmq.exchange.sales-delete-request=${RABBITMQ_EXCHANGE_SALES_DELETE_REQUEST:sales.delete.request.exchange}
rabbitmq.queue.sales-delete-request=${RABBITMQ_QUEUE_SALES_DELETE_REQUEST:sales.delete.request.queue}
rabbitmq.routing-key.sales-delete-request=${RABBITMQ_ROUTING_KEY_SALES_DELETE_REQUEST:sales.delete.request}
