spring.config.import=optional:file:.env[.properties]

# Exchange y Queue
rabbitmq.exchange.commercial=${RABBITMQ_EXCHANGE_COMMERCIAL:commercial.exchange}
rabbitmq.queue.purchase=${RABBITMQ_QUEUE_PURCHASE:purchase.queue}
rabbitmq.routing-key.purchase=${RABBITMQ_ROUTING_KEY_PURCHASE:purchase.received}
# Sales Create
rabbitmq.exchange.sales-create-request=${RABBITMQ_EXCHANGE_SALES_CREATE_REQUEST:sales.create.request.exchange}
rabbitmq.queue.sales-create-request=${RABBITMQ_QUEUE_SALES_CREATE_REQUEST:sales.create.request.queue}
rabbitmq.routing-key.sales-create-request=${RABBITMQ_ROUTING_KEY_SALES_CREATE_REQUEST:sales.create.request}
# Sales Update
rabbitmq.exchange.sales-update-request=${RABBITMQ_EXCHANGE_SALES_UPDATE_REQUEST:sales.update.request.exchange}
rabbitmq.queue.sales-update-request=${RABBITMQ_QUEUE_SALES_UPDATE_REQUEST:sales.update.request.queue}
rabbitmq.routing-key.sales-update-request=${RABBITMQ_ROUTING_KEY_SALES_UPDATE_REQUEST:sales.update.request}
# Sales Patch
rabbitmq.exchange.sales-patch-request=${RABBITMQ_EXCHANGE_SALES_PATCH_REQUEST:sales.patch.request.exchange}
rabbitmq.queue.sales-patch-request=${RABBITMQ_QUEUE_SALES_PATCH_REQUEST:sales.patch.request.queue}
rabbitmq.routing-key.sales-patch-request=${RABBITMQ_ROUTING_KEY_SALES_PATCH_REQUEST:sales.patch.request}
# Sales Delete
rabbitmq.exchange.sales-delete-request=${RABBITMQ_EXCHANGE_SALES_DELETE_REQUEST:sales.delete.request.exchange}
rabbitmq.queue.sales-delete-request=${RABBITMQ_QUEUE_SALES_DELETE_REQUEST:sales.delete.request.queue}
rabbitmq.routing-key.sales-delete-request=${RABBITMQ_ROUTING_KEY_SALES_DELETE_REQUEST:sales.delete.request}

# Table CRUD
rabbitmq.queue.table-crud=${RABBITMQ_QUEUE_TABLE_CRUD:table.crud.queue}
rabbitmq.routing-key.table-crud=${RABBITMQ_ROUTING_KEY_TABLE_CRUD:table.crud.routing-key}
# Table Session
rabbitmq.queue.table-session=${RABBITMQ_QUEUE_TABLE_SESSION:table.session.queue}
rabbitmq.routing-key.table-session=${RABBITMQ_ROUTING_KEY_TABLE_SESSION:table.session.routing-key}
# Table Reservation
rabbitmq.queue.table-reservation=${RABBITMQ_QUEUE_TABLE_RESERVATION:table.reservation.queue}
rabbitmq.routing-key.table-reservation=${RABBITMQ_ROUTING_KEY_TABLE_RESERVATION:table.reservation.routing-key}
# Discount
rabbitmq.queue.discount=${RABBITMQ_QUEUE_DISCOUNT:discount.queue}
rabbitmq.routing-key.discount=${RABBITMQ_ROUTING_KEY_DISCOUNT:discount.events}

# CustomerDiscount
rabbitmq.queue.customer-discount=${RABBITMQ_QUEUE_CUSTOMER_DISCOUNT:customer.discount.queue}
rabbitmq.routing-key.customer-discount=${RABBITMQ_ROUTING_KEY_CUSTOMER_DISCOUNT:customer.discount.events}

# Seller
rabbitmq.queue.seller=${RABBITMQ_QUEUE_SELLER:seller.queue}
rabbitmq.routing-key.seller=${RABBITMQ_ROUTING_KEY_SELLER:seller.events}

# Email
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
