rabbitmq.exchange.product=product.exchange

rabbitmq.queue.product.create=product.create.queue
rabbitmq.queue.product.update=product.update.queue
rabbitmq.queue.product.stock=product.stock.queue
rabbitmq.queue.product.patch=product.patch.queue
rabbitmq.queue.product.delete=product.delete.queue

rabbitmq.routing-key.product.create=product.create.requested
rabbitmq.routing-key.product.update=product.update.requested
rabbitmq.routing-key.product.stock=product.stock.updated
rabbitmq.routing-key.product.patch=product.patch.requested
rabbitmq.routing-key.product.delete=product.delete.requested