spring.config.import=optional:file:.env[.properties]


rabbitmq.exchange.product=product.exchange

rabbitmq.queue.product.create=product.create.queue
rabbitmq.queue.product.update=product.update.queue
rabbitmq.queue.product.stock=product.stock.queue
rabbitmq.queue.product.patch=product.patch.queue
rabbitmq.queue.product.delete=product.delete.queue

rabbitmq.routing-key.product.create=product.create.requested
rabbitmq.routing-key.product.update=product.update.requested
rabbitmq.routing-key.product.stock=product.stock.updated
rabbitmq.routing-key.product.patch=product.patch.requested
rabbitmq.routing-key.product.delete=product.delete.requested


rabbitmq.exchange.location=${RABBITMQ_EXCHANGE_LOCATION:location.exchange}

rabbitmq.queue.location.create=${RABBITMQ_QUEUE_LOCATION_CREATE:location.create}
rabbitmq.queue.location.update=${RABBITMQ_QUEUE_LOCATION_UPDATE:location.update}
rabbitmq.queue.location.patch=${RABBITMQ_QUEUE_LOCATION_PATCH:location.patch}

rabbitmq.routing-key.location.create=${RABBITMQ_ROUTING_KEY_LOCATION_CREATE:location.create}
rabbitmq.routing-key.location.update=${RABBITMQ_ROUTING_KEY_LOCATION_UPDATE:location.update}
rabbitmq.routing-key.location.patch=${RABBITMQ_ROUTING_KEY_LOCATION_PATCH:location.patch}

# RabbitMQ - módulo transfer
rabbitmq.exchange.transfer.request=create.transfer.request.exchange
rabbitmq.exchange.transfer.response=create.transfer.response.exchange
rabbitmq.exchange.transfer.status.request=update.transfer.status.request.exchange

rabbitmq.queue.transfer.request=create.transfer.request.queue
rabbitmq.queue.transfer.response=create.transfer.response.queue
rabbitmq.queue.transfer.status.request=update.transfer.status.request.queue

rabbitmq.routing-key.transfer.request=create.transfer.request
rabbitmq.routing-key.transfer.response=create.transfer.response
rabbitmq.routing-key.transfer.status.request=update.transfer.status.request

#RECIPE
rabbitmq.exchange.recipe=recipe.exchange

rabbitmq.queue.recipe.create=recipe.create.queue
rabbitmq.queue.recipe.update=recipe.update.queue
rabbitmq.queue.recipe.patch=recipe.patch.queue

rabbitmq.routing-key.recipe.create=recipe.create.requested
rabbitmq.routing-key.recipe.update=recipe.update.requested
rabbitmq.routing-key.recipe.patch=recipe.patch.requested

# RabbitMQ - modulo category
rabbitmq.exchange.category=${RABBITMQ_EXCHANGE_CATEGORY:category.exchange}
rabbitmq.exchange.category.dlx=${RABBITMQ_EXCHANGE_CATEGORY_DLX:category.dlx}

rabbitmq.queue.category.create=${RABBITMQ_QUEUE_CATEGORY_CREATE:category.create.queue}
rabbitmq.queue.category.update-status=${RABBITMQ_QUEUE_CATEGORY_UPDATE_STATUS:category.update-status.queue}
rabbitmq.queue.category.create.dlq=${RABBITMQ_QUEUE_CATEGORY_CREATE_DLQ:category.create.dlq}
rabbitmq.queue.category.update-status.dlq=${RABBITMQ_QUEUE_CATEGORY_UPDATE_STATUS_DLQ:category.update-status.dlq}

rabbitmq.routing-key.category.create=${RABBITMQ_ROUTING_KEY_CATEGORY_CREATE:category.create}
rabbitmq.routing-key.category.update-status=${RABBITMQ_ROUTING_KEY_CATEGORY_UPDATE_STATUS:category.update-status}
rabbitmq.routing-key.category.create.dlq=${RABBITMQ_ROUTING_KEY_CATEGORY_CREATE_DLQ:category.create.dlq}
rabbitmq.routing-key.category.update-status.dlq=${RABBITMQ_ROUTING_KEY_CATEGORY_UPDATE_STATUS_DLQ:category.update-status.dlq}


