spring.config.import=optional:file:.env[.properties]

# Exchange y Queues del modulo payment
rabbitmq.exchange.payment=${RABBITMQ_EXCHANGE_PAYMENT:payment.exchange}
rabbitmq.queue.payment.cashreceipt.create=${RABBITMQ_QUEUE_PAYMENT_CASHRECEIPT_CREATE:payment.cashreceipt.create.queue}
rabbitmq.queue.payment.cashreceipt.cancel=${RABBITMQ_QUEUE_PAYMENT_CASHRECEIPT_CANCEL:payment.cashreceipt.cancel.queue}
rabbitmq.routing-key.payment.cashreceipt.create=${RABBITMQ_ROUTING_KEY_PAYMENT_CASHRECEIPT_CREATE:payment.cashreceipt.create}
rabbitmq.routing-key.payment.cashreceipt.cancel=${RABBITMQ_ROUTING_KEY_PAYMENT_CASHRECEIPT_CANCEL:payment.cashreceipt.cancel}

rabbitmq.queue.payment.invoice.create=${RABBITMQ_QUEUE_PAYMENT_INVOICE_CREATE:payment.invoice.create.queue}
rabbitmq.queue.payment.invoice.cancel=${RABBITMQ_QUEUE_PAYMENT_INVOICE_CANCEL:payment.invoice.cancel.queue}
rabbitmq.queue.payment.invoice.mark-paid=${RABBITMQ_QUEUE_PAYMENT_INVOICE_MARK_PAID:payment.invoice.mark-paid.queue}
rabbitmq.queue.payment.invoice.status-update=${RABBITMQ_QUEUE_PAYMENT_INVOICE_STATUS_UPDATE:payment.invoice.status-update.queue}

rabbitmq.routing-key.payment.invoice.create=${RABBITMQ_ROUTING_KEY_PAYMENT_INVOICE_CREATE:payment.invoice.create}
rabbitmq.routing-key.payment.invoice.cancel=${RABBITMQ_ROUTING_KEY_PAYMENT_INVOICE_CANCEL:payment.invoice.cancel}
rabbitmq.routing-key.payment.invoice.mark-paid=${RABBITMQ_ROUTING_KEY_PAYMENT_INVOICE_MARK_PAID:payment.invoice.mark-paid}
rabbitmq.routing-key.payment.invoice.status-update=${RABBITMQ_ROUTING_KEY_PAYMENT_INVOICE_STATUS_UPDATE:payment.invoice.status-update}
