spring.config.import=optional:file:.env[.properties]

# Exchange y Queue
rabbitmq.exchange.user=${RABBITMQ_EXCHANGE_USER:user.exchange}
rabbitmq.queue.user=${RABBITMQ_QUEUE_USER:user.queue}
rabbitmq.routing-key.user=${RABBITMQ_ROUTING_KEY_USER:user.command}
